name: fitforfree
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.0.1
  flutter_screenutil: ^5.9.0
  flutter_feather_icons: ^2.0.0+1
  google_fonts: ^6.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  carousel_slider: ^4.2.1
  motion_tab_bar_v2: ^0.3.0
  http: ^1.1.2
  accordion: ^2.6.0
  comment_box: ^0.0.18
  smooth_page_indicator: ^1.1.0
  searchable_listview: ^2.10.0
  signalr_netcore: ^0.1.7+2-nullsafety.3
  tiny_charts: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/mainTemp.jpeg
